### PR TITLE
Add: support to run reward loop during OS

### PR DESCRIPTION
**Pull request by nEEtdo0d**
Pretty straight forward, check and runs reward loop before going for a zone clear. Been using this myself for the past few monthly resets.

I'll keep the PR open for a few days to gauge whether this is the direction to go with or preferably use a separate instance rather than inheritance like
```
import Reward
backup = ...
check = Reward(...)
if check.handle_reward():
    ....
backup.recover()
```

If no particular backlash, I can make the merge official.

### CODE REVIEW

**Comment by nEEtdo0d** [comment]
RIP, because of shop module inherited by Reward I used the same method signature, this overrides the os_shop methods. So have to use the standalone instance method.

**Comment by LmeSzinc** [comment]
You can rename methods in module/os_handler/shop.py to `os_shop_xxx()`, and rename `ShopHandler` to `OSShopHandler`

**Comment by nEEtdo0d** [comment]
> You can rename methods in module/os_handler/shop.py to `os_shop_xxx()`, and rename `ShopHandler` to `OSShopHandler`

Gotcha then we can maintain the overall direction in that case. Didn't want to overstep, thanks.

**Comment by nEEtdo0d** [comment]
Pushed directly to master to minimize commit history

**Pull request closed without merging**
