### PR TITLE
Linux + Docker support

### PR DESCRIPTION
**Pull request by viperML**
For easier Linux support, I have writting a small Dockerfile that allows any user to install the environment needed for ALAS, without polluting their environment. I have also added a script which automates this process. In theory, MacOS and Windows users should be able to follow the same steps, although I don't have a mac machine to test it.

By using docker's host networking, the GUI is accesible via a web browser and ADB inside the container can access any emulator running on the host machine.

I am also adding a section in the wiki to show how to use it, under some [EXPERIMENTAL] headings.

### CODE REVIEW

**Comment by LmeSzinc** [comment]
Have you finished writing the wiki? The last edit date is Nov. 22.
After the completion, this PR will be merged.

**Comment by viperML** [comment]
Sorry for the delay, I was trying to push my locally edited wiki repo but got permission denied, instead of directly editing it through the web.

The article is now ready in its own page https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_en_docker , and referenced before the `Manual Install` section in https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/Installation_en

**Comment by viperML** [comment]
Is there any way to upload some screenshots into the wiki?

**Comment by LmeSzinc** [comment]
Quickly looked through the web page of github wiki. It's seems there isn't a way to upload images, unless using 3rd party image hosting. I sent you a collabrator invitation, should solve the permission issue by accepting it.

**Comment by viperML** [comment]
Thanks, I have just uploaded the screenshots (all of them related to the emulator installation)

**Pull request merged**
