### PR TITLE
Upd:[TW] Angel of Iris

### PR DESCRIPTION
**Pull request by xzjjasper**
请先别merge
虽然所有资源都替换了，但仍然无法运行，劳烦lme佬帮我看看问题在哪

### CODE REVIEW

**Comment by LmeSzinc** [comment]
`module/raid/raid.py` 里面 `raid_ocr` 等函数也可能要改，运行不了发 log

**Comment by xzjjasper** [comment]
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
                                                       RAIDDAILY                                                       
═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
2023-03-23 20:52:52.659 | INFO | Current hosts: ['10.0.4.12', '10.253.0.1']                                            
2023-03-23 20:52:52.661 | INFO | Connecting to local network device, using host 10.253.0.1                             
2023-03-23 20:52:52.664 | INFO | Reverse server listening on 10.253.0.1:20408, client can send data to 10.253.0.1:20408
2023-03-23 20:52:52.706 | INFO | sdk_ver: 27                                                                           
2023-03-23 20:52:52.738 | INFO | [nc command] ['nc']                                                                   
2023-03-23 20:52:53.410 | INFO | [Screen_size] 720x1280                                                                
2023-03-23 20:52:53.413 | INFO | Received orientated screenshot, handling                                              
2023-03-23 20:52:53.446 | INFO | [Device Orientation] 1 (HOME key on the right)                                        
2023-03-23 20:52:53.452 | INFO | [Screen_size] 1280x720                                                                
2023-03-23 20:52:53.532 | INFO | <<< UI ENSURE >>>                                                                     
2023-03-23 20:52:53.535 | INFO | UI get current page                                                                   
2023-03-23 20:52:53.914 | INFO | Unknown ui page                                                                       
2023-03-23 20:52:53.927 | INFO | Click (1229,   34) @ GOTO_MAIN                                                        
2023-03-23 20:52:53.930 | INFO | <<< MINITOUCH INIT >>>                                                                
2023-03-23 20:52:53.973 | INFO | [Device Orientation] 1 (HOME key on the right)                                        
2023-03-23 20:52:53.978 | INFO | Create forward: ForwardItem(serial='10.253.0.2:5555', local='tcp:20525',              
remote='localabstract:minitouch')                                                                                      
2023-03-23 20:52:53.992 | INFO | v 1                                                                                   
2023-03-23 20:52:53.994 | INFO | ^ 10 720 1280 0                                                                       
2023-03-23 20:52:53.996 | INFO | $ 3989                                                                                
2023-03-23 20:52:53.997 | INFO | minitouch running on port: 20525, pid: 3989                                           
2023-03-23 20:52:53.999 | INFO | max_contact: 10; max_x: 720; max_y: 1280; max_pressure: 0                             
2023-03-23 20:52:54.493 | INFO | Unknown ui page                                                                       
2023-03-23 20:52:54.895 | INFO | [u2.Device] Device(atx_agent_url=http://127.0.0.1:50418)                              
2023-03-23 20:52:54.967 | INFO | [Package_name] com.hkmanjuu.azurlane.gp.mc                                            
2023-03-23 20:52:54.999 | INFO | [Device Orientation] 1 (HOME key on the right)                                        
2023-03-23 20:52:55.846 | INFO | [UI] page_main                                                                        
2023-03-23 20:52:55.849 | INFO | Goto page_raid                                                                        
2023-03-23 20:52:55.851 | INFO | <<< UI GOTO PAGE_RAID >>>                                                             
2023-03-23 20:52:55.868 | INFO | Page switch: page_main -> page_raid                                                   
2023-03-23 20:52:55.871 | INFO | Click ( 639,  283) @ MAIN_GOTO_RAID                                                   
2023-03-23 20:56:35.197 | WARNING | Wait too long                                                                      
2023-03-23 20:56:35.198 | WARNING | Waiting for {'DORM_FEED_CANCEL', 'DORM_TROPHY_CONFIRM', 'STORY_SKIP_2',            
'LOGIN_ANNOUNCE', 'EVENT_CHECK', 'COMMISSION_CHECK', 'RESEARCH_CHECK', 'MAIN_GOTO_CAMPAIGN', 'SHOP_CHECK', 'GET_SHIP', 
'AUTO_SEARCH_MENU_EXIT', 'DORMMENU_CHECK', 'PURCHASE_POPUP', 'EVENT_LIST_CHECK', 'GAME_TIPS', 'SP_CHECK',              
'MAP_PREPARATION', 'MONTHLY_PASS_NOTICE', 'WAR_ARCHIVES_CHECK', 'CAMPAIGN_CHECK', 'FLEET_PREPARATION', 'STORY_SKIP',   
'BATTLE_PASS_NOTICE', 'GUILD_CHECK', 'OS_CHECK', 'EXERCISE_PREPARATION', 'SHIPYARD_CHECK', 'SUPPLY_PACK_CHECK',        
'DORM_CHECK', 'EXERCISE_CHECK', 'DORM_INFO', 'BUILD_CHECK', 'RESET_FLEET_PREPARATION', 'FLEET_CHECK', 'META_CHECK',    
'RESHMENU_CHECK', 'STORAGE_CHECK', 'GET_MISSION', 'GET_ITEMS_1', 'PLAYER_CHECK', 'REWARD_CHECK', 'MEOWFFICER_INFO',    
'MEOWFFICER_CHECK', 'EXCHANGE_CHECK', 'RAID_CHECK', 'LOGIN_RETURN_SIGN', 'WITHDRAW', 'LOGIN_CHECK', 'POPUP_CANCEL',    
'GUILD_POPUP_CONFIRM', 'AUTO_SEARCH_REWARD', 'BATTLE_PASS_CHECK', 'DAILY_CHECK', 'ACADEMY_CHECK', 'MISSION_CHECK',     
'CAMPAIGN_MENU_CHECK', 'RAID_FLEET_PREPARATION', 'MUNITIONS_CHECK', 'RESET_TICKET_POPUP', 'TACTICAL_CHECK'}            
2023-03-23 20:56:35.260 | INFO | [Package_name] com.hkmanjuu.azurlane.gp.mc                                            
2023-03-23 20:56:35.262 | ERROR | GameStuckError: Wait too long                                                        
2023-03-23 20:56:35.266 | WARNING | Saving error: ./log/error/1679576195266

**Comment by LmeSzinc** [comment]
需要更新 RAID_CHECK

**Comment by xzjjasper** [comment]
补充一个做assets的图片
Screenshot_2023 03 23_19 54 34 851

**Comment by xzjjasper** [comment]
这次识别没问题，但是进入出击准备界面后会触发task balance（无论是否勾选此选项），推迟共斗任务。是正常现象么？
log：
``` 
RAIDDAILY                                     
═══════════════════════════════════════════════════════════════════════════════════
INFO     21:34:22.159 │ Current hosts: ['10.0.4.12', '10.253.0.1']                 
INFO     21:34:22.161 │ Connecting to local network device, using host 10.253.0.1  
INFO     21:34:22.162 │ Reverse server listening on 10.253.0.1:20919, client can   
         send data to 10.253.0.1:20919                                             
INFO     21:34:22.191 │ sdk_ver: 27                                                
INFO     21:34:22.219 │ [nc command] ['nc']                                        
INFO     21:34:22.831 │ [Screen_size] 720x1280                                     
INFO     21:34:22.833 │ Received orientated screenshot, handling                   
INFO     21:34:22.872 │ [Device Orientation] 1 (HOME key on the right)             
INFO     21:34:22.879 │ [Screen_size] 1280x720                                     
INFO     21:34:22.971 │ <<< UI ENSURE >>>                                          
INFO     21:34:22.974 │ UI get current page                                        
INFO     21:34:22.995 │ [UI] page_main                                             
INFO     21:34:22.997 │ Goto page_raid                                             
INFO     21:34:23.000 │ <<< UI GOTO PAGE_RAID >>>                                  
INFO     21:34:23.182 │ Page switch: page_main -> page_raid                        
INFO     21:34:23.185 │ Click ( 631,  287) @ MAIN_GOTO_RAID                        
INFO     21:34:23.188 │ <<< MINITOUCH INIT >>>                                     
INFO     21:34:23.221 │ [Device Orientation] 1 (HOME key on the right)             
INFO     21:34:23.224 │ Reuse forward: ForwardItem(serial='10.253.0.2:5555',       
         local='tcp:20085', remote='localabstract:minitouch')                      
INFO     21:34:23.246 │ v 1                                                        
INFO     21:34:23.248 │ ^ 10 720 1280 0                                            
INFO     21:34:23.250 │ $ 3989                                                     
INFO     21:34:23.251 │ minitouch running on port: 20085, pid: 3989                
INFO     21:34:23.253 │ max_contact: 10; max_x: 720; max_y: 1280; max_pressure: 0  
INFO     21:34:25.461 │ Page arrive: page_raid                                     
══════════════════════════════════════ HARD ═══════════════════════════════════════
INFO     21:34:25.465 │ HARD                                                       
INFO     21:34:25.488 │ Loading OCR model: ./bin/cnocr_models/cnocr                
INFO     21:34:25.610 │ [IRIS_OCR_REMAIN_HARD 0.144s] 12/15                        
INFO     21:34:25.612 │ [Hard Remain] 12                                           
INFO     21:34:26.734 │ [IRIS_OCR_REMAIN_HARD 0.063s] 12/15                        
INFO     21:34:26.736 │ [Hard Remain] 12                                           
─────────────────────────────── RAID_20220630_HARD ────────────────────────────────
INFO     21:34:26.739 │ RAID_20220630_HARD                                         
INFO     21:34:26.741 │ Count: 0                                                   
INFO     21:34:26.743 │ <<< UI ENSURE >>>                                          
INFO     21:34:26.744 │ UI get current page                                        
INFO     21:34:26.762 │ [UI] page_raid                                             
INFO     21:34:26.765 │ Already at page_raid                                       
INFO     21:34:26.766 │ <<< RAID EXECUTE >>>                                       
INFO     21:34:26.768 │ Expect emotion reduce: (2, 0)                              
INFO     21:34:26.792 │ Bind task {'EventGeneral', 'RaidDaily', 'General', 'Alas', 
         'TaskBalancer'}                                                           
INFO     21:34:26.794 │ Save config ./config\alas.json,                            
         RaidDaily.Emotion.Fleet1Value=119,                                        
         RaidDaily.Emotion.Fleet1Record=datetime.datetime(2023, 3, 23, 21, 34, 26),
         RaidDaily.Emotion.Fleet2Value=119,                                        
         RaidDaily.Emotion.Fleet2Record=datetime.datetime(2023, 3, 23, 21, 34, 26) 
INFO     21:34:26.809 │ [Emotion fleet_1] 119                                      
INFO     21:34:26.811 │ [Emotion fleet_2] 119                                      
INFO     21:34:26.824 │ Click (1131,  313) @ IRIS_RAID_HARD                        
INFO     21:34:28.991 │ Click (1070,  595) @ RAID_FLEET_PREPARATION                
INFO     21:34:30.890 │ Combat preparation.                                        
INFO     21:34:30.913 │ Loading OCR model: ./bin/cnocr_models/azur_lane            
INFO     21:34:31.007 │ [OCR_OIL 0.113s] 12667                                     
INFO     21:34:31.010 │ Delay task `RaidDaily` to 2023-03-23 21:39:31 (minute=5)   
INFO     21:34:31.028 │ Bind task {'EventGeneral', 'RaidDaily', 'General', 'Alas', 
         'TaskBalancer'}                                                           
INFO     21:34:31.030 │ Save config ./config\alas.json,                            
         RaidDaily.Scheduler.NextRun=datetime.datetime(2023, 3, 23, 21, 39, 31)    
INFO     21:34:31.046 │ <<< TASKBALANCER TRIGGERED, SWITCHING TASK TO MAIN2 >>>    
INFO     21:34:31.048 │ Task call: Main2                                           
INFO     21:34:31.077 │ Bind task {'EventGeneral', 'RaidDaily', 'General', 'Alas', 
         'TaskBalancer'}                                                           
INFO     21:34:31.080 │ Save config ./config\alas.json,                            
         Main2.Scheduler.NextRun=datetime.datetime(2023, 3, 23, 21, 34, 31),       
         Main2.Scheduler.Enable=True                                               
INFO     21:34:31.108 │ Scheduler: End task `RaidDaily`                            
INFO     21:34:31.111 │ [Server] tw                                                
INFO     21:34:31.137 │ Bind task {'Alas', 'General'}                              
INFO     21:34:31.152 │ Pending tasks: ['Main', 'Main2', 'GemsFarming']            
INFO     21:34:31.154 │ [Task] Main (Enable, 2023-03-23 21:32:00)                  
INFO     21:34:31.156 │ Bind task {'Main', 'Alas', 'General'}                      
INFO     21:34:31.175 │ Scheduler: Start task `Main`

**Comment by LmeSzinc** [comment]
```python
@run_once
        def check_coin():
            self.handle_task_balancer()
```
self.handle_task_balancer() 改成：
```python
            if self.config.TaskBalancer_Enable and self.triggered_task_balancer():
                logger.hr('Triggered stop condition: Coin limit')
                self.handle_task_balancer()
                return True
```

**Comment by xzjjasper** [comment]
已测试通过

**Comment by LmeSzinc** [comment]
IRIS_OCR_PT 保持不变，你改了之后的长度不够，上6位数就溢出了

**Pull request merged**
