### PR TITLE
Upd: [EN] assets and allow for gorizia ex auto raid

### PR DESCRIPTION
**Pull request by nEEtdo0d**
Trivial asset updates for EN

Other servers may need their own variant or if for some reason the font color is different for ex raid

### CODE REVIEW

**Comment by bookbug666** [comment]
There's no ocr issue in EN? I tried crop my own/use your EN version to test stage EX in JP server, and here's (part of) the result
```INFO     11:45:16.256 │ RAID_20230629_EX                                      
INFO     11:45:16.257 │ Count remain: 1                                       
INFO     11:45:16.258 │ <<< UI ENSURE >>>                                     
INFO     11:45:16.258 │ UI get current page                                   
INFO     11:45:16.354 │ [UI] page_raid                                        
INFO     11:45:16.355 │ Already at page_raid                                  
INFO     11:45:16.366 │ Loading OCR model: ./bin/cnocr_models/azur_lane       
INFO     11:45:16.414 │ [GORIZIA_OCR_REMAIN_EX 0.059s] 1                      
WARNING  11:45:16.415 │ Unexpected ocr result: 1                              
INFO     11:45:16.416 │ [Ex Remain] (0, 0, 0)                                 
INFO     11:45:16.789 │ [GORIZIA_OCR_REMAIN_EX 0.016s] 1                      
WARNING  11:45:16.790 │ Unexpected ocr result: 1                              
INFO     11:45:16.791 │ [Ex Remain] (0, 0, 0)                                 
INFO     11:45:16.791 │ <<< RAID EXECUTE >>>                                  
```
Having no idea how to fix this :(

**Comment by nEEtdo0d** [comment]
> There's no ocr issue in EN? I tried crop my own/use your EN version to test stage EX in JP server, and here's (part of) the result
> 
> ```
> INFO     11:45:16.257 │ Count remain: 1                                       
> INFO     11:45:16.258 │ <<< UI ENSURE >>>                                     
> INFO     11:45:16.258 │ UI get current page                                   
> INFO     11:45:16.354 │ [UI] page_raid                                        
> INFO     11:45:16.355 │ Already at page_raid                                  
> INFO     11:45:16.366 │ Loading OCR model: ./bin/cnocr_models/azur_lane       
> INFO     11:45:16.414 │ [GORIZIA_OCR_REMAIN_EX 0.059s] 1                      
> WARNING  11:45:16.415 │ Unexpected ocr result: 1                              
> INFO     11:45:16.416 │ [Ex Remain] (0, 0, 0)                                 
> INFO     11:45:16.789 │ [GORIZIA_OCR_REMAIN_EX 0.016s] 1                      
> WARNING  11:45:16.790 │ Unexpected ocr result: 1                              
> INFO     11:45:16.791 │ [Ex Remain] (0, 0, 0)                                 
> INFO     11:45:16.791 │ <<< RAID EXECUTE >>>                                  
> ```
> 
> Having no idea how to fix this :(

That is bizarre.
```
────────────────────────────────────────────────── RAID_20230629_EX ───────────────────────────────────────────────────
2023-06-30 17:38:19.805 | INFO | RAID_20230629_EX                                                                      
2023-06-30 17:38:19.807 | INFO | Count: 5                                                                              
2023-06-30 17:38:19.809 | INFO | <<< UI ENSURE >>>                                                                     
2023-06-30 17:38:19.811 | INFO | UI get current page                                                                   
2023-06-30 17:38:19.833 | INFO | [UI] page_raid                                                                        
2023-06-30 17:38:19.838 | INFO | Already at page_raid                                                                  
2023-06-30 17:38:19.909 | INFO | [GORIZIA_OCR_REMAIN_EX 0.065s] 1                                                      
2023-06-30 17:38:19.913 | INFO | [Ex Remain] 1                                                                         
2023-06-30 17:38:20.419 | INFO | [GORIZIA_OCR_REMAIN_EX 0.053s] 1                                                      
2023-06-30 17:38:20.423 | INFO | [Ex Remain] 1                                                                         
2023-06-30 17:38:20.424 | INFO | <<< RAID EXECUTE >>>                                     
```

From what I can tell, it is using DigitCounter. Maybe something I didn't consider but do you have JSON config like this?
```
    "RaidDaily": {
      "StageFilter": "hard > ex"
```

**Comment by bookbug666** [comment]
Nope, I was testing the ocr in `Raid` rather than `RaidDaily`
[EX.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/11924385/EX.zip)

I also tried extending the border, no help but get the same result.

**Comment by nEEtdo0d** [comment]
> Nope, I was testing the ocr in `Raid` rather than `RaidDaily` [EX.zip](https://github.com/LmeSzinc/AzurLaneAutoScript/files/11924385/EX.zip)
> 
> I also tried extending the border, no help but get the same result.

```
═══════════════════════════════════════════════════════════════════════════════════
                                       RAID                                        
═══════════════════════════════════════════════════════════════════════════════════
──────────────────────────────── RAID_20230629_EX ─────────────────────────────────
INFO     00:08:46.295 │ RAID_20230629_EX                                           
INFO     00:08:46.298 │ Count: 0                                                   
INFO     00:08:46.300 │ <<< UI ENSURE >>>                                          
INFO     00:08:46.304 │ UI get current page                                        
INFO     00:08:46.323 │ [UI] page_raid                                             
INFO     00:08:46.327 │ Already at page_raid                                       
INFO     00:08:46.364 │ [GORIZIA_OCR_REMAIN_EX 0.034s] 0                           
INFO     00:08:46.367 │ [Ex Remain] 0                                              
INFO     00:08:46.702 │ [GORIZIA_OCR_REMAIN_EX 0.033s] 0                           
INFO     00:08:46.705 │ [Ex Remain] 0                                              
INFO     00:08:46.707 │ Triggered stop condition: Zero raid tickets to do EX mode  
INFO     00:08:46.710 │ Scheduler: End task `Raid`                              
```

Normal raid works for me too. Since its printing `(0, 0, 0)` on in your screenshot I still think its using DigitCounter.

Other factors to consider is the asset itself, font color, and that threshold value in the snippet. In the same area as that snippet, there was a time where EN was using bolder text than other servers for example.

**Comment by nEEtdo0d** [comment]
Thanks for helping me to discover a bug in the normal Raid task, don't use it often so didn't realize it went into a infinite loop.

It doesn't for RaidDaily since its wrapped.

**Comment by nEEtdo0d** [comment]
Bizarre, I am not able to reproduce or see how you are getting `(0, 0, 0)` in that log of yours.  The code shouldn't result in that, it should still have pulled out a 0 at least normally not a tuple like its printing. So very strange.

One last thing to try is maybe shrinking the border, honing to the number I think helps. Give enough border room for 2 digits I'd say. I tend to cut big but if I don't come across any issues I'll keep as is.

**Comment by bookbug666** [comment]
GORIZIA_OCR_REMAIN_EX
```
═══════════════════════════════════════════════════════════════════════════════════
                                       RAID                                        
═══════════════════════════════════════════════════════════════════════════════════
──────────────────────────────── RAID_20230629_EX ─────────────────────────────────
INFO     13:38:52.962 │ RAID_20230629_EX                                           
INFO     13:38:52.962 │ Count remain: 1                                            
INFO     13:38:52.963 │ <<< UI ENSURE >>>                                          
INFO     13:38:52.964 │ UI get current page                                        
INFO     13:38:52.973 │ [UI] page_commission                                       
INFO     13:38:52.974 │ Goto page_raid                                             
INFO     13:38:52.975 │ <<< UI GOTO PAGE_RAID >>>                                  
INFO     13:38:52.982 │ Page switch: page_commission -> page_main                  
INFO     13:38:52.983 │ Click (1238,   34) @ GOTO_MAIN                             
INFO     13:38:53.383 │ Page switch: page_main -> page_raid                        
INFO     13:38:53.384 │ Click ( 620,  283) @ MAIN_GOTO_RAID                        
INFO     13:38:54.532 │ Page arrive: page_raid                                     
INFO     13:38:54.552 │ [GORIZIA_OCR_REMAIN_EX 0.019s] 11                          
WARNING  13:38:54.553 │ Unexpected ocr result: 11                                  
INFO     13:38:54.554 │ [Ex Remain] (0, 0, 0)                                      
INFO     13:38:54.917 │ [GORIZIA_OCR_REMAIN_EX 0.013s] 11                          
WARNING  13:38:54.918 │ Unexpected ocr result: 11                                  
INFO     13:38:54.920 │ [Ex Remain] (0, 0, 0)                                      
INFO     13:38:54.921 │ <<< RAID EXECUTE >>>                                       
INFO     13:38:54.922 │ Expect emotion reduce: (2, 0)                              
INFO     13:38:54.932 │ Bind task {'Raid', 'General', 'Alas', 'TaskBalancer',      
         'EventGeneral'}                                                           
INFO     13:38:54.934 │ Save config ./config\alas.json,                            
         Raid.Emotion.Fleet1Value=150,                                             
         Raid.Emotion.Fleet1Record=datetime.datetime(2023, 7, 1, 13, 38, 54),      
         Raid.Emotion.Fleet2Value=119,                                             
         Raid.Emotion.Fleet2Record=datetime.datetime(2023, 7, 1, 13, 38, 54)       
INFO     13:38:55.007 │ [Emotion fleet_1] 150                                      
INFO     13:38:55.009 │ [Emotion fleet_2] 119                                      
INFO     13:38:55.017 │ Click (1023,  221) @ GORIZIA_RAID_EX                       
INFO     13:38:55.572 │ Click (1124,  591) @ RAID_FLEET_PREPARATION                
INFO     13:38:56.540 │ Combat preparation.                                        
INFO     13:38:56.572 │ [OCR_OIL 0.023s] 14066                                     
INFO     13:38:56.599 │ Click (1113,  641) @ BATTLE_PREPARATION                    
INFO     13:38:58.647 │ Click (1238,  633) @ BATTLE_PREPARATION                    
[alas] exited. Reason: Manual stop
```
I "borrowed" the crop area from another raid event(the `KUYBYSHEY_OCR_REMAIN_EX.png` in the CN folder), and I get `11` now.
The border room is definitely enough for 2 digits, what the heck.

**Pull request merged**
